name: test

on:
  push:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.0"
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - name: Run
        shell: bash
        run: |
          ./test.sh
